//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_DAD_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operatie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operatie()
        {
            this.Rulajes = new myBindingColl<Rulaje>();
        }
    
        public int id { get; set; }
        public Nullable<int> Numar { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Doc { get; set; }
        public Nullable<System.DateTime> DataDoc { get; set; }
        public string Explicatie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual myBindingColl<Rulaje> Rulajes { get; set; }
    }
}
