//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_DAD_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rulaje
    {
        public int id { get; set; }
        public Nullable<int> idCont { get; set; }
        public Nullable<int> idOperatie { get; set; }
        public Nullable<double> SumaD { get; set; }
        public Nullable<double> SumaC { get; set; }
    
        public virtual Cont Cont { get; set; }
        public virtual Operatie Operatie { get; set; }
    }
}
